version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: cleaning_service_redis
    ports:
      - "6380:6379"
  api:
    build: .
    container_name: cleaning_service_api
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:3081594@localhost:5432/paul-clean-bd
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=YOUR_SECRET_KEY_HERE
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - WORKING_HOURS_START=10:00
      - WORKING_HOURS_END=19:00
      - SLOT_DURATION_MINUTES=30
      - CORS_ORIGINS=["http://localhost:8080", "https://www.localhost:8080","https://preview--sparkle-shuttle.lovable.app","https://www.preview--sparkle-shuttle.lovable.app"]
      - SMTP_SERVER=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_USERNAME=apikey
      - SMTP_PASSWORD=YOUR_SENDGRID_API_KEY_HERE
      - SMTP_TLS=true
      - SMTP_STARTTLS=true
      - EMAIL_VERIFICATION_REQUIRED=true
      - EMAIL_VERIFICATION_TOKEN_EXPIRE_HOURS=24
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
    network_mode: host
