#!/usr/bin/env python3
"""
Test script for debugging JWT tokens
"""

from jose import jwt
from app.config import settings

def test_token_creation():
    """Test token creation"""
    print("🔧 Testing token creation...")
    
    data = {"sub": "6", "type": "access"}
    print(f"Data: {data}")
    print(f"Secret key: {settings.secret_key[:20]}...")
    print(f"Algorithm: {settings.algorithm}")
    
    try:
        token = jwt.encode(data, settings.secret_key, algorithm=settings.algorithm)
        print(f"✅ Token created: {token[:50]}...")
        return token
    except Exception as e:
        print(f"❌ Error creating token: {e}")
        return None

def test_token_verification(token):
    """Test token verification"""
    print(f"\n🔍 Testing token verification...")
    print(f"Token: {token[:50]}...")
    
    try:
        payload = jwt.decode(token, settings.secret_key, algorithms=[settings.algorithm])
        print(f"✅ Token verified: {payload}")
        return payload
    except jwt.ExpiredSignatureError:
        print("❌ Token expired")
        return None
    except jwt.InvalidTokenError as e:
        print(f"❌ Invalid token: {e}")
        return None
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return None

def test_existing_token():
    """Test the token that was generated by the API"""
    print(f"\n🧪 Testing existing API token...")
    
    # This is the token from the API response
    api_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwidHlwZSI6ImFjY2VzcyIsImV4cCI6MTc1NTgyNDMzMn0.s6qQjP85GIJZ9o1M6fEAAJH7gE33YZQW-83voIHe71o"
    
    try:
        payload = jwt.decode(api_token, settings.secret_key, algorithms=[settings.algorithm])
        print(f"✅ API token verified: {payload}")
        return payload
    except jwt.ExpiredSignatureError:
        print("❌ API token expired")
        return None
    except jwt.InvalidTokenError as e:
        print(f"❌ API token invalid: {e}")
        return None
    except Exception as e:
        print(f"❌ Unexpected error with API token: {e}")
        return None

if __name__ == "__main__":
    print("🧪 JWT Token Test")
    print("=" * 50)
    
    # Test token creation
    token = test_token_creation()
    
    if token:
        # Test token verification
        payload = test_token_verification(token)
        
        if payload:
            print("\n✅ All tests passed!")
        else:
            print("\n❌ Token verification failed!")
    else:
        print("\n❌ Token creation failed!")
    
    # Test existing API token
    test_existing_token()
