name: Deploy to Production Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests'
        required: false
        default: 'false'
        type: boolean

# Environment variables moved to secrets for security

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tests }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: always() && (needs.test.result == 'success' || inputs.skip_tests)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        
    - name: Create deployment backup
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Создаем резервную копию текущего состояния
          BACKUP_DIR="/opt/backups/$(date +%Y%m%d_%H%M%S)"
          mkdir -p "$BACKUP_DIR"
          
          if [ -f "data/cleaning_service_stable.db" ]; then
            cp data/cleaning_service_stable.db "$BACKUP_DIR/"
          fi
          
          # Сохраняем текущую версию Git
          git rev-parse HEAD > "$BACKUP_DIR/previous_commit.txt" 2>/dev/null || echo "unknown" > "$BACKUP_DIR/previous_commit.txt"
          
          echo "BACKUP_DIR=$BACKUP_DIR" > /tmp/backup_info.txt
        EOF
        
    - name: Deploy application
      run: |
        # Копируем файлы на сервер
        rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519" \
          --exclude='.git' \
          --exclude='__pycache__' \
          --exclude='*.pyc' \
          --exclude='.env' \
          --exclude='data/' \
          ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/
        
        # Выполняем деплой на сервере
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Настраиваем SSH для GitHub
          mkdir -p ~/.ssh
          echo "${{ secrets.GITHUB_SSH_KEY }}" > ~/.ssh/github_key
          chmod 600 ~/.ssh/github_key
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          
          # Настраиваем SSH config для GitHub
          cat > ~/.ssh/config << 'SSH_CONFIG'
          Host github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/github_key
            IdentitiesOnly yes
          SSH_CONFIG
          
          # Обновляем git репозиторий
          git fetch origin main
          git reset --hard origin/main
          
          # Сохраняем текущий коммит
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Deploying commit: $CURRENT_COMMIT"
          
          # Останавливаем сервисы
          docker-compose -f docker-compose.stable.yml down
          
          # Запускаем новые сервисы
          docker-compose -f docker-compose.stable.yml up -d --build
          
          # Ждем запуска
          sleep 30
          
          # Применяем миграции базы данных
          echo "🔄 Применяем миграции базы данных..."
          docker-compose -f docker-compose.stable.yml exec -T cleaning_service_api_stable alembic upgrade head
          
          # Проверяем статус контейнеров
          if ! docker-compose -f docker-compose.stable.yml ps | grep -q "Up"; then
            echo "❌ Контейнеры не запустились!"
            exit 1
          fi
          
          # Проверяем здоровье API
          for i in {1..10}; do
            if curl -f http://localhost:8000/health > /dev/null 2>&1; then
              echo "✅ API здоров!"
              break
            fi
            echo "⏳ Ожидание API... ($i/10)"
            sleep 10
          done
          
          if ! curl -f http://localhost:8000/health > /dev/null 2>&1; then
            echo "❌ API не отвечает после 100 секунд!"
            exit 1
          fi
          
          echo "✅ Деплой завершен успешно!"
          echo "COMMIT: $CURRENT_COMMIT"
        EOF
        
    - name: Health check
      run: |
        # Дополнительная проверка здоровья
        for i in {1..5}; do
          if curl -f http://${{ secrets.SERVER_HOST }}:8000/health > /dev/null 2>&1; then
            echo "✅ Внешняя проверка API прошла успешно!"
            exit 0
          fi
          echo "⏳ Повторная проверка... ($i/5)"
          sleep 10
        done
        
        echo "❌ API недоступен снаружи!"
        exit 1
        
    - name: Rollback on failure
      if: failure()
      run: |
        echo "🔄 Выполняем откат..."
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Останавливаем проблемные сервисы
          docker-compose -f docker-compose.stable.yml down
          
          # Восстанавливаем из резервной копии
          BACKUP_DIR=$(find /opt/backups -type d -name "*" | sort | tail -1)
          if [ -d "$BACKUP_DIR" ] && [ -f "$BACKUP_DIR/cleaning_service_stable.db" ]; then
            cp "$BACKUP_DIR/cleaning_service_stable.db" data/
            echo "✅ База данных восстановлена из резервной копии"
          fi
          
          # Запускаем предыдущую версию
          docker-compose -f docker-compose.stable.yml up -d
          
          echo "🔄 Откат завершен"
        EOF
        
    - name: Deployment summary
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🚀 Деплой завершен успешно!"
          echo "📊 Статус: ✅ Успех"
        else
          echo "❌ Деплой завершился с ошибкой!"
          echo "📊 Статус: ❌ Ошибка"
        fi
